
version: 2

models:
    - name: customer_data
      description: "raw customer data"
      columns:
          - name: customer_id
            description: "customer identification number"
            tests:
                - not_null

    - name: analytics
      description: "analytical data"
      columns:
          - name: customer_id
            description: "customer identification number"
            tests:
                - not_null
          - name: first_name
            description: "customer first name"
            tests:
                - not_null
